# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# extract_values_to_points.py
# Created on: 2014-11-28 11:00:58.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
pontos_kml_to_shp_UTM_z23 = "pontos_kml_to_shp_UTM_z23"
kernel_estradas_100_img = "kernel_estradas_100.img"
pontos_extract_kernel_100_shp = "F:\\data\\john_pc2\\Marinana\\Analises\\shps_pontos_extrac_densitys\\estradas\\pontos_extract_kernel_100.shp"

# Process: Extract Values to Points
arcpy.gp.ExtractValuesToPoints_sa(pontos_kml_to_shp_UTM_z23, kernel_estradas_100_img, pontos_extract_kernel_100_shp, "NONE", "VALUE_ONLY")

