# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# select_by_atributes.py
# Created on: 2015-01-09 15:22:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
buffer_1000 = "buffer_1000"

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(buffer_1000, "NEW_SELECTION", "\"name\" = '1'")

