# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# union.py
# Created on: 2014-12-24 00:48:26.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
buffer_0100_clip_Uso = "buffer_0100_clip_Uso"
buffer_100 = "buffer_100"
union_teste_shp = "F:\\data\\john_pc2\\Marinana\\Analises\\buffer_clip_uso\\union_teste.shp"

# Process: Union
arcpy.Union_analysis("buffer_0100_clip_Uso #;buffer_100 #", union_teste_shp, "ALL", "", "GAPS")

