# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# zonal.py
# Created on: 2014-11-20 15:23:08.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
buffer_100 = "buffer_100"
v23S48_SN_tif = "23S48_SN.tif"
ZonalSt_shp3 = "C:\\Users\\John\\Documents\\ArcGIS\\Default.gdb\\ZonalSt_shp3"

# Process: Zonal Statistics
arcpy.gp.ZonalStatistics_sa(buffer_100, "name", v23S48_SN_tif, ZonalSt_shp3, "MEAN", "DATA")

