# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# zonalastable.py
# Created on: 2014-11-20 15:46:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
buffer_750 = "buffer_750"
v23S48_dleciv_tif = "23S48_dleciv.tif"
ZonalSt_shp4 = "C:\\Users\\John\\Documents\\ArcGIS\\Default.gdb\\ZonalSt_shp4"

# Process: Zonal Statistics as Table
arcpy.gp.ZonalStatisticsAsTable_sa(buffer_750, "name", v23S48_dleciv_tif, ZonalSt_shp4, "DATA", "ALL")

